// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_4_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        hw_output_V_value_V,
        hw_output_V_value_V_ap_vld,
        hw_output_V_value_V_ap_ack,
        hw_output_V_last_V,
        hw_output_V_last_V_ap_vld,
        hw_output_V_last_V_ap_ack,
        p_mul_stencil_stream_V_value_V_dout,
        p_mul_stencil_stream_V_value_V_empty_n,
        p_mul_stencil_stream_V_value_V_read,
        p_delayed_input_stencil_stream_V_value_V_dout,
        p_delayed_input_stencil_stream_V_value_V_empty_n,
        p_delayed_input_stencil_stream_V_value_V_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state6 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [7:0] hw_output_V_value_V;
output   hw_output_V_value_V_ap_vld;
input   hw_output_V_value_V_ap_ack;
output  [0:0] hw_output_V_last_V;
output   hw_output_V_last_V_ap_vld;
input   hw_output_V_last_V_ap_ack;
input  [31:0] p_mul_stencil_stream_V_value_V_dout;
input   p_mul_stencil_stream_V_value_V_empty_n;
output   p_mul_stencil_stream_V_value_V_read;
input  [31:0] p_delayed_input_stencil_stream_V_value_V_dout;
input   p_delayed_input_stencil_stream_V_value_V_empty_n;
output   p_delayed_input_stencil_stream_V_value_V_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg hw_output_V_value_V_ap_vld;
reg hw_output_V_last_V_ap_vld;
reg p_mul_stencil_stream_V_value_V_read;
reg p_delayed_input_stencil_stream_V_value_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    hw_output_V_value_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0_flag00000000;
reg   [0:0] exitcond_flatten_reg_312;
reg   [0:0] ap_reg_pp0_iter2_exitcond_flatten_reg_312;
reg    hw_output_V_last_V_blk_n;
reg    p_mul_stencil_stream_V_value_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    p_delayed_input_stencil_stream_V_value_V_blk_n;
reg   [20:0] indvar_flatten_reg_100;
reg   [10:0] p_hw_output_y_scan_1_reg_111;
reg   [10:0] p_hw_output_x_scan_2_reg_123;
wire   [0:0] exitcond_flatten_fu_134_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    ap_sig_ioackin_hw_output_V_value_V_ap_ack;
reg    ap_block_state5_io;
reg    ap_block_pp0_stage0_flag00011001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_flatten_reg_312;
wire   [20:0] indvar_flatten_next_fu_140_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond7_fu_146_p2;
reg   [0:0] exitcond7_reg_321;
reg   [0:0] ap_reg_pp0_iter1_exitcond7_reg_321;
reg   [0:0] ap_reg_pp0_iter2_exitcond7_reg_321;
wire   [10:0] p_hw_output_x_scan_s_fu_152_p3;
reg   [10:0] p_hw_output_x_scan_s_reg_327;
wire   [10:0] p_hw_output_x_scan_1_fu_160_p2;
wire   [10:0] p_hw_output_y_scan_2_fu_166_p2;
reg   [10:0] p_hw_output_y_scan_2_reg_337;
wire   [0:0] tmp_1_fu_172_p2;
reg   [0:0] tmp_1_reg_342;
reg   [0:0] ap_reg_pp0_iter2_tmp_1_reg_342;
wire   [10:0] p_hw_output_y_scan_s_fu_178_p3;
reg   [10:0] p_hw_output_y_scan_s_reg_347;
wire   [7:0] p_471_fu_185_p1;
reg   [7:0] p_471_reg_352;
reg   [7:0] ap_reg_pp0_iter2_p_471_reg_352;
wire   [7:0] p_475_fu_209_p2;
reg   [7:0] p_475_reg_357;
reg   [7:0] ap_reg_pp0_iter2_p_475_reg_357;
reg   [3:0] tmp_12_reg_363;
reg   [3:0] tmp_13_reg_368;
wire   [0:0] tmp_s_fu_235_p2;
reg   [0:0] tmp_s_reg_373;
reg   [0:0] ap_reg_pp0_iter2_tmp_s_reg_373;
wire   [0:0] tmp_3_mid1_fu_240_p2;
reg   [0:0] tmp_3_mid1_reg_378;
wire   [0:0] p_478_fu_245_p2;
reg   [0:0] p_478_reg_383;
wire   [0:0] p_480_fu_250_p2;
reg   [0:0] p_480_reg_388;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg   [10:0] p_hw_output_y_scan_1_phi_fu_115_p4;
reg    ap_block_pp0_stage0_flag00001001;
reg    ap_reg_ioackin_hw_output_V_value_V_ap_ack;
reg    ap_reg_ioackin_hw_output_V_last_V_ap_ack;
wire   [3:0] p_s_fu_189_p4;
wire   [7:0] p_474_fu_199_p1;
wire   [7:0] p_479_fu_203_p2;
wire   [1:0] tmp_14_fu_269_p4;
wire   [1:0] tmp_15_fu_278_p3;
wire   [5:0] tmp_fu_260_p4;
wire   [5:0] tmp_5_cast_fu_285_p1;
wire   [5:0] p_483_fu_289_p3;
wire   [7:0] p_483_cast_fu_296_p1;
wire   [0:0] tmp_3_mid2_fu_255_p3;
wire    ap_CS_fsm_state6;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_reg_ioackin_hw_output_V_value_V_ap_ack = 1'b0;
#0 ap_reg_ioackin_hw_output_V_last_V_ap_ack = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 ^ 1'b1);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_312 == 1'd0))) begin
            if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b0;
            end else if (((ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b1 == hw_output_V_last_V_ap_ack))) begin
                ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_312 == 1'd0))) begin
            if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b0;
            end else if (((ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b1 == hw_output_V_value_V_ap_ack))) begin
                ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_134_p2))) begin
        indvar_flatten_reg_100 <= indvar_flatten_next_fu_140_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        indvar_flatten_reg_100 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_134_p2))) begin
        p_hw_output_x_scan_2_reg_123 <= p_hw_output_x_scan_1_fu_160_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        p_hw_output_x_scan_2_reg_123 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_312) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        p_hw_output_y_scan_1_reg_111 <= p_hw_output_y_scan_s_reg_347;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        p_hw_output_y_scan_1_reg_111 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_exitcond7_reg_321 <= exitcond7_reg_321;
        ap_reg_pp0_iter1_exitcond_flatten_reg_312 <= exitcond_flatten_reg_312;
        exitcond_flatten_reg_312 <= exitcond_flatten_fu_134_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
        ap_reg_pp0_iter2_exitcond7_reg_321 <= ap_reg_pp0_iter1_exitcond7_reg_321;
        ap_reg_pp0_iter2_exitcond_flatten_reg_312 <= ap_reg_pp0_iter1_exitcond_flatten_reg_312;
        ap_reg_pp0_iter2_p_471_reg_352 <= p_471_reg_352;
        ap_reg_pp0_iter2_p_475_reg_357 <= p_475_reg_357;
        ap_reg_pp0_iter2_tmp_1_reg_342 <= tmp_1_reg_342;
        ap_reg_pp0_iter2_tmp_s_reg_373 <= tmp_s_reg_373;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_flatten_fu_134_p2))) begin
        exitcond7_reg_321 <= exitcond7_fu_146_p2;
        p_hw_output_x_scan_s_reg_327 <= p_hw_output_x_scan_s_fu_152_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_312 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_471_reg_352 <= p_471_fu_185_p1;
        p_475_reg_357 <= p_475_fu_209_p2;
        p_hw_output_y_scan_2_reg_337 <= p_hw_output_y_scan_2_fu_166_p2;
        tmp_12_reg_363 <= {{p_475_fu_209_p2[7:4]}};
        tmp_13_reg_368 <= {{p_479_fu_203_p2[7:4]}};
        tmp_s_reg_373 <= tmp_s_fu_235_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_312))) begin
        p_478_reg_383 <= p_478_fu_245_p2;
        p_480_reg_388 <= p_480_fu_250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_312 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_hw_output_y_scan_s_reg_347 <= p_hw_output_y_scan_s_fu_178_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_312 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond7_reg_321))) begin
        tmp_1_reg_342 <= tmp_1_fu_172_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_312) & (ap_reg_pp0_iter1_exitcond7_reg_321 == 1'd1))) begin
        tmp_3_mid1_reg_378 <= tmp_3_mid1_fu_240_p2;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_134_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_hw_output_V_value_V_ap_ack)) begin
        ap_sig_ioackin_hw_output_V_value_V_ap_ack = hw_output_V_value_V_ap_ack;
    end else begin
        ap_sig_ioackin_hw_output_V_value_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_312 == 1'd0) & (ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_hw_output_V_last_V_ap_ack))) begin
        hw_output_V_last_V_ap_vld = 1'b1;
    end else begin
        hw_output_V_last_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (ap_reg_pp0_iter2_exitcond_flatten_reg_312 == 1'd0))) begin
        hw_output_V_last_V_blk_n = hw_output_V_last_V_ap_ack;
    end else begin
        hw_output_V_last_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_312 == 1'd0) & (ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_hw_output_V_value_V_ap_ack))) begin
        hw_output_V_value_V_ap_vld = 1'b1;
    end else begin
        hw_output_V_value_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (ap_reg_pp0_iter2_exitcond_flatten_reg_312 == 1'd0))) begin
        hw_output_V_value_V_blk_n = hw_output_V_value_V_ap_ack;
    end else begin
        hw_output_V_value_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_312 == 1'd0))) begin
        p_delayed_input_stencil_stream_V_value_V_blk_n = p_delayed_input_stencil_stream_V_value_V_empty_n;
    end else begin
        p_delayed_input_stencil_stream_V_value_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_312 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_delayed_input_stencil_stream_V_value_V_read = 1'b1;
    end else begin
        p_delayed_input_stencil_stream_V_value_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_312) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        p_hw_output_y_scan_1_phi_fu_115_p4 = p_hw_output_y_scan_s_reg_347;
    end else begin
        p_hw_output_y_scan_1_phi_fu_115_p4 = p_hw_output_y_scan_1_reg_111;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_312 == 1'd0))) begin
        p_mul_stencil_stream_V_value_V_blk_n = p_mul_stencil_stream_V_value_V_empty_n;
    end else begin
        p_mul_stencil_stream_V_value_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_312 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_mul_stencil_stream_V_value_V_read = 1'b1;
    end else begin
        p_mul_stencil_stream_V_value_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_flatten_fu_134_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_flatten_fu_134_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_mul_stencil_stream_V_value_V_empty_n)) | ((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_delayed_input_stencil_stream_V_value_V_empty_n))));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_mul_stencil_stream_V_value_V_empty_n)) | ((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_delayed_input_stencil_stream_V_value_V_empty_n)))) | ((1'b1 == ap_enable_reg_pp0_iter3) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_mul_stencil_stream_V_value_V_empty_n)) | ((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_delayed_input_stencil_stream_V_value_V_empty_n)))) | ((1'b1 == ap_enable_reg_pp0_iter3) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = (((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_mul_stencil_stream_V_value_V_empty_n)) | ((exitcond_flatten_reg_312 == 1'd0) & (1'b0 == p_delayed_input_stencil_stream_V_value_V_empty_n)));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((ap_reg_pp0_iter2_exitcond_flatten_reg_312 == 1'd0) & (1'b0 == ap_sig_ioackin_hw_output_V_value_V_ap_ack));
end

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond7_fu_146_p2 = ((p_hw_output_x_scan_2_reg_123 == 11'd1918) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_134_p2 = ((indvar_flatten_reg_100 == 21'd2067604) ? 1'b1 : 1'b0);

assign hw_output_V_last_V = (ap_reg_pp0_iter2_tmp_s_reg_373 & tmp_3_mid2_fu_255_p3);

assign hw_output_V_value_V = (p_483_cast_fu_296_p1 + ap_reg_pp0_iter2_p_471_reg_352);

assign indvar_flatten_next_fu_140_p2 = (indvar_flatten_reg_100 + 21'd1);

assign p_471_fu_185_p1 = p_delayed_input_stencil_stream_V_value_V_dout[7:0];

assign p_474_fu_199_p1 = p_s_fu_189_p4;

assign p_475_fu_209_p2 = (p_471_fu_185_p1 - p_474_fu_199_p1);

assign p_478_fu_245_p2 = ((tmp_12_reg_363 != 4'd0) ? 1'b1 : 1'b0);

assign p_479_fu_203_p2 = (p_474_fu_199_p1 - p_471_fu_185_p1);

assign p_480_fu_250_p2 = ((tmp_13_reg_368 != 4'd0) ? 1'b1 : 1'b0);

assign p_483_cast_fu_296_p1 = p_483_fu_289_p3;

assign p_483_fu_289_p3 = ((p_478_reg_383[0:0] === 1'b1) ? tmp_fu_260_p4 : tmp_5_cast_fu_285_p1);

assign p_hw_output_x_scan_1_fu_160_p2 = (11'd1 + p_hw_output_x_scan_s_fu_152_p3);

assign p_hw_output_x_scan_s_fu_152_p3 = ((exitcond7_fu_146_p2[0:0] === 1'b1) ? 11'd0 : p_hw_output_x_scan_2_reg_123);

assign p_hw_output_y_scan_2_fu_166_p2 = (11'd1 + p_hw_output_y_scan_1_phi_fu_115_p4);

assign p_hw_output_y_scan_s_fu_178_p3 = ((exitcond7_reg_321[0:0] === 1'b1) ? p_hw_output_y_scan_2_fu_166_p2 : p_hw_output_y_scan_1_phi_fu_115_p4);

assign p_s_fu_189_p4 = {{p_mul_stencil_stream_V_value_V_dout[7:4]}};

assign tmp_14_fu_269_p4 = {{ap_reg_pp0_iter2_p_475_reg_357[3:2]}};

assign tmp_15_fu_278_p3 = ((p_480_reg_388[0:0] === 1'b1) ? tmp_14_fu_269_p4 : 2'd0);

assign tmp_1_fu_172_p2 = ((p_hw_output_y_scan_1_phi_fu_115_p4 == 11'd1077) ? 1'b1 : 1'b0);

assign tmp_3_mid1_fu_240_p2 = ((p_hw_output_y_scan_2_reg_337 == 11'd1077) ? 1'b1 : 1'b0);

assign tmp_3_mid2_fu_255_p3 = ((ap_reg_pp0_iter2_exitcond7_reg_321[0:0] === 1'b1) ? tmp_3_mid1_reg_378 : ap_reg_pp0_iter2_tmp_1_reg_342);

assign tmp_5_cast_fu_285_p1 = tmp_15_fu_278_p3;

assign tmp_fu_260_p4 = {{ap_reg_pp0_iter2_p_475_reg_357[7:2]}};

assign tmp_s_fu_235_p2 = ((p_hw_output_x_scan_s_reg_327 == 11'd1917) ? 1'b1 : 1'b0);

endmodule //Loop_4_proc
