// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_1_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_hw_input_stencil_stream_V_value_V_dout,
        p_hw_input_stencil_stream_V_value_V_empty_n,
        p_hw_input_stencil_stream_V_value_V_read,
        hw_output_V_value_V,
        hw_output_V_value_V_ap_vld,
        hw_output_V_value_V_ap_ack,
        hw_output_V_last_V,
        hw_output_V_last_V_ap_vld,
        hw_output_V_last_V_ap_ack
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [287:0] p_hw_input_stencil_stream_V_value_V_dout;
input   p_hw_input_stencil_stream_V_value_V_empty_n;
output   p_hw_input_stencil_stream_V_value_V_read;
output  [31:0] hw_output_V_value_V;
output   hw_output_V_value_V_ap_vld;
input   hw_output_V_value_V_ap_ack;
output  [0:0] hw_output_V_last_V;
output   hw_output_V_last_V_ap_vld;
input   hw_output_V_last_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_hw_input_stencil_stream_V_value_V_read;
reg hw_output_V_value_V_ap_vld;
reg hw_output_V_last_V_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_hw_input_stencil_stream_V_value_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_flag00000000;
reg   [0:0] exitcond_flatten_reg_405;
reg    hw_output_V_value_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] ap_reg_pp0_iter3_exitcond_flatten_reg_405;
reg    hw_output_V_last_V_blk_n;
reg   [20:0] indvar_flatten_reg_126;
reg   [10:0] p_hw_output_y_scan_1_reg_137;
reg   [10:0] p_hw_output_x_scan_2_reg_149;
wire   [0:0] exitcond_flatten_fu_160_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg    ap_sig_ioackin_hw_output_V_value_V_ap_ack;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_flag00011001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_flatten_reg_405;
reg   [0:0] ap_reg_pp0_iter2_exitcond_flatten_reg_405;
wire   [20:0] indvar_flatten_next_fu_166_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond_fu_172_p2;
reg   [0:0] exitcond_reg_414;
reg   [0:0] ap_reg_pp0_iter1_exitcond_reg_414;
reg   [0:0] ap_reg_pp0_iter2_exitcond_reg_414;
wire   [10:0] p_hw_output_x_scan_s_fu_178_p3;
reg   [10:0] p_hw_output_x_scan_s_reg_420;
wire   [10:0] p_hw_output_x_scan_1_fu_186_p2;
wire   [10:0] p_hw_output_y_scan_2_fu_192_p2;
reg   [10:0] p_hw_output_y_scan_2_reg_430;
wire   [0:0] tmp8_fu_198_p2;
reg   [0:0] tmp8_reg_435;
reg   [0:0] ap_reg_pp0_iter2_tmp8_reg_435;
wire   [10:0] p_hw_output_y_scan_s_fu_204_p3;
reg   [10:0] p_hw_output_y_scan_s_reg_440;
wire   [31:0] p_345_fu_211_p1;
reg   [31:0] p_345_reg_445;
reg   [31:0] p_357_reg_450;
reg   [31:0] ap_reg_pp0_iter2_p_357_reg_450;
reg   [31:0] p_381_reg_455;
reg   [31:0] p_393_reg_460;
reg   [30:0] tmp_2_reg_465;
reg   [30:0] tmp_4_reg_470;
reg   [30:0] ap_reg_pp0_iter2_tmp_4_reg_470;
reg   [29:0] tmp_5_reg_475;
reg   [30:0] tmp_6_reg_480;
reg   [30:0] tmp_7_reg_485;
wire   [0:0] tmp_s_fu_295_p2;
reg   [0:0] tmp_s_reg_490;
reg   [0:0] ap_reg_pp0_iter2_tmp_s_reg_490;
wire   [0:0] tmp_mid1_fu_300_p2;
reg   [0:0] tmp_mid1_reg_495;
wire   [31:0] tmp2_fu_333_p2;
reg   [31:0] tmp2_reg_500;
wire   [31:0] tmp5_fu_338_p2;
reg   [31:0] tmp5_reg_505;
reg   [31:0] ap_reg_pp0_iter3_tmp5_reg_505;
wire   [31:0] tmp6_fu_349_p2;
reg   [31:0] tmp6_reg_510;
reg   [31:0] ap_reg_pp0_iter3_tmp6_reg_510;
wire   [31:0] tmp1_fu_371_p2;
reg   [31:0] tmp1_reg_515;
wire   [0:0] tmp_last_V_fu_376_p2;
reg   [0:0] tmp_last_V_reg_520;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [10:0] p_hw_output_y_scan_1_phi_fu_141_p4;
reg    ap_block_pp0_stage0_flag00001001;
reg    ap_reg_ioackin_hw_output_V_value_V_ap_ack;
reg    ap_reg_ioackin_hw_output_V_last_V_ap_ack;
wire   [31:0] p_353_fu_305_p3;
wire   [31:0] p_377_fu_319_p3;
wire   [31:0] p_371_fu_312_p3;
wire   [31:0] p_389_fu_326_p3;
wire   [31:0] tmp7_fu_344_p2;
wire   [31:0] p_365_fu_359_p3;
wire   [31:0] tmp3_fu_366_p2;
wire   [0:0] tmp_mid2_fu_354_p3;
wire   [31:0] tmp4_fu_381_p2;
wire   [31:0] p_397_fu_385_p2;
wire   [27:0] tmp_3_fu_390_p4;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_reg_ioackin_hw_output_V_value_V_ap_ack = 1'b0;
#0 ap_reg_ioackin_hw_output_V_last_V_ap_ack = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state7)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 ^ 1'b1);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_405))) begin
            if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b0;
            end else if (((ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b1 == hw_output_V_last_V_ap_ack))) begin
                ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_405))) begin
            if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b0;
            end else if (((ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b1 == hw_output_V_value_V_ap_ack))) begin
                ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_160_p2))) begin
        indvar_flatten_reg_126 <= indvar_flatten_next_fu_166_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        indvar_flatten_reg_126 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_160_p2))) begin
        p_hw_output_x_scan_2_reg_149 <= p_hw_output_x_scan_1_fu_186_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        p_hw_output_x_scan_2_reg_149 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_405) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        p_hw_output_y_scan_1_reg_137 <= p_hw_output_y_scan_s_reg_440;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        p_hw_output_y_scan_1_reg_137 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_exitcond_flatten_reg_405 <= exitcond_flatten_reg_405;
        ap_reg_pp0_iter1_exitcond_reg_414 <= exitcond_reg_414;
        exitcond_flatten_reg_405 <= exitcond_flatten_fu_160_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
        ap_reg_pp0_iter2_exitcond_flatten_reg_405 <= ap_reg_pp0_iter1_exitcond_flatten_reg_405;
        ap_reg_pp0_iter2_exitcond_reg_414 <= ap_reg_pp0_iter1_exitcond_reg_414;
        ap_reg_pp0_iter2_p_357_reg_450 <= p_357_reg_450;
        ap_reg_pp0_iter2_tmp8_reg_435 <= tmp8_reg_435;
        ap_reg_pp0_iter2_tmp_4_reg_470 <= tmp_4_reg_470;
        ap_reg_pp0_iter2_tmp_s_reg_490 <= tmp_s_reg_490;
        ap_reg_pp0_iter3_exitcond_flatten_reg_405 <= ap_reg_pp0_iter2_exitcond_flatten_reg_405;
        ap_reg_pp0_iter3_tmp5_reg_505[31 : 1] <= tmp5_reg_505[31 : 1];
        ap_reg_pp0_iter3_tmp6_reg_510 <= tmp6_reg_510;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_flatten_fu_160_p2))) begin
        exitcond_reg_414 <= exitcond_fu_172_p2;
        p_hw_output_x_scan_s_reg_420 <= p_hw_output_x_scan_s_fu_178_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_405 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_345_reg_445 <= p_345_fu_211_p1;
        p_357_reg_450 <= {{p_hw_input_stencil_stream_V_value_V_dout[95:64]}};
        p_381_reg_455 <= {{p_hw_input_stencil_stream_V_value_V_dout[223:192]}};
        p_393_reg_460 <= {{p_hw_input_stencil_stream_V_value_V_dout[287:256]}};
        p_hw_output_y_scan_2_reg_430 <= p_hw_output_y_scan_2_fu_192_p2;
        tmp_2_reg_465 <= {{p_hw_input_stencil_stream_V_value_V_dout[62:32]}};
        tmp_4_reg_470 <= {{p_hw_input_stencil_stream_V_value_V_dout[126:96]}};
        tmp_5_reg_475 <= {{p_hw_input_stencil_stream_V_value_V_dout[157:128]}};
        tmp_6_reg_480 <= {{p_hw_input_stencil_stream_V_value_V_dout[190:160]}};
        tmp_7_reg_485 <= {{p_hw_input_stencil_stream_V_value_V_dout[254:224]}};
        tmp_s_reg_490 <= tmp_s_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_405 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_hw_output_y_scan_s_reg_440 <= p_hw_output_y_scan_s_fu_204_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter2_exitcond_flatten_reg_405))) begin
        tmp1_reg_515 <= tmp1_fu_371_p2;
        tmp_last_V_reg_520 <= tmp_last_V_fu_376_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_405))) begin
        tmp2_reg_500 <= tmp2_fu_333_p2;
        tmp5_reg_505[31 : 1] <= tmp5_fu_338_p2[31 : 1];
        tmp6_reg_510 <= tmp6_fu_349_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (exitcond_flatten_reg_405 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_reg_414))) begin
        tmp8_reg_435 <= tmp8_fu_198_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_405) & (ap_reg_pp0_iter1_exitcond_reg_414 == 1'd1))) begin
        tmp_mid1_reg_495 <= tmp_mid1_fu_300_p2;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_160_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3) & (1'b0 == ap_enable_reg_pp0_iter4))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_hw_output_V_value_V_ap_ack)) begin
        ap_sig_ioackin_hw_output_V_value_V_ap_ack = hw_output_V_value_V_ap_ack;
    end else begin
        ap_sig_ioackin_hw_output_V_value_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_405) & (ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_hw_output_V_last_V_ap_ack))) begin
        hw_output_V_last_V_ap_vld = 1'b1;
    end else begin
        hw_output_V_last_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_405))) begin
        hw_output_V_last_V_blk_n = hw_output_V_last_V_ap_ack;
    end else begin
        hw_output_V_last_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_405) & (ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_hw_output_V_value_V_ap_ack))) begin
        hw_output_V_value_V_ap_vld = 1'b1;
    end else begin
        hw_output_V_value_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter4) & (1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_405))) begin
        hw_output_V_value_V_blk_n = hw_output_V_value_V_ap_ack;
    end else begin
        hw_output_V_value_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (exitcond_flatten_reg_405 == 1'd0))) begin
        p_hw_input_stencil_stream_V_value_V_blk_n = p_hw_input_stencil_stream_V_value_V_empty_n;
    end else begin
        p_hw_input_stencil_stream_V_value_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_405 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_hw_input_stencil_stream_V_value_V_read = 1'b1;
    end else begin
        p_hw_input_stencil_stream_V_value_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_405) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        p_hw_output_y_scan_1_phi_fu_141_p4 = p_hw_output_y_scan_s_reg_440;
    end else begin
        p_hw_output_y_scan_1_phi_fu_141_p4 = p_hw_output_y_scan_1_reg_137;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter4) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_flatten_fu_160_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter4) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_flatten_fu_160_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_405 == 1'd0) & (1'b0 == p_hw_input_stencil_stream_V_value_V_empty_n));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011001 = (((1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_405 == 1'd0) & (1'b0 == p_hw_input_stencil_stream_V_value_V_empty_n)) | ((1'b1 == ap_enable_reg_pp0_iter4) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011011 = (((1'b1 == ap_enable_reg_pp0_iter1) & (exitcond_flatten_reg_405 == 1'd0) & (1'b0 == p_hw_input_stencil_stream_V_value_V_empty_n)) | ((1'b1 == ap_enable_reg_pp0_iter4) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((exitcond_flatten_reg_405 == 1'd0) & (1'b0 == p_hw_input_stencil_stream_V_value_V_empty_n));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((1'd0 == ap_reg_pp0_iter3_exitcond_flatten_reg_405) & (1'b0 == ap_sig_ioackin_hw_output_V_value_V_ap_ack));
end

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond_flatten_fu_160_p2 = ((indvar_flatten_reg_126 == 21'd2067604) ? 1'b1 : 1'b0);

assign exitcond_fu_172_p2 = ((p_hw_output_x_scan_2_reg_149 == 11'd1918) ? 1'b1 : 1'b0);

assign hw_output_V_last_V = tmp_last_V_reg_520;

assign hw_output_V_value_V = $signed(tmp_3_fu_390_p4);

assign indvar_flatten_next_fu_166_p2 = (indvar_flatten_reg_126 + 21'd1);

assign p_345_fu_211_p1 = p_hw_input_stencil_stream_V_value_V_dout[31:0];

assign p_353_fu_305_p3 = {{tmp_2_reg_465}, {1'd0}};

assign p_365_fu_359_p3 = {{ap_reg_pp0_iter2_tmp_4_reg_470}, {1'd0}};

assign p_371_fu_312_p3 = {{tmp_5_reg_475}, {2'd0}};

assign p_377_fu_319_p3 = {{tmp_6_reg_480}, {1'd0}};

assign p_389_fu_326_p3 = {{tmp_7_reg_485}, {1'd0}};

assign p_397_fu_385_p2 = (tmp1_reg_515 + tmp4_fu_381_p2);

assign p_hw_output_x_scan_1_fu_186_p2 = (11'd1 + p_hw_output_x_scan_s_fu_178_p3);

assign p_hw_output_x_scan_s_fu_178_p3 = ((exitcond_fu_172_p2[0:0] === 1'b1) ? 11'd0 : p_hw_output_x_scan_2_reg_149);

assign p_hw_output_y_scan_2_fu_192_p2 = (11'd1 + p_hw_output_y_scan_1_phi_fu_141_p4);

assign p_hw_output_y_scan_s_fu_204_p3 = ((exitcond_reg_414[0:0] === 1'b1) ? p_hw_output_y_scan_2_fu_192_p2 : p_hw_output_y_scan_1_phi_fu_141_p4);

assign tmp1_fu_371_p2 = (tmp2_reg_500 + tmp3_fu_366_p2);

assign tmp2_fu_333_p2 = (p_345_reg_445 + p_353_fu_305_p3);

assign tmp3_fu_366_p2 = (p_365_fu_359_p3 + ap_reg_pp0_iter2_p_357_reg_450);

assign tmp4_fu_381_p2 = (ap_reg_pp0_iter3_tmp5_reg_505 + ap_reg_pp0_iter3_tmp6_reg_510);

assign tmp5_fu_338_p2 = (p_377_fu_319_p3 + p_371_fu_312_p3);

assign tmp6_fu_349_p2 = (p_381_reg_455 + tmp7_fu_344_p2);

assign tmp7_fu_344_p2 = (p_393_reg_460 + p_389_fu_326_p3);

assign tmp8_fu_198_p2 = ((p_hw_output_y_scan_1_phi_fu_141_p4 == 11'd1077) ? 1'b1 : 1'b0);

assign tmp_3_fu_390_p4 = {{p_397_fu_385_p2[31:4]}};

assign tmp_last_V_fu_376_p2 = (ap_reg_pp0_iter2_tmp_s_reg_490 & tmp_mid2_fu_354_p3);

assign tmp_mid1_fu_300_p2 = ((p_hw_output_y_scan_2_reg_430 == 11'd1077) ? 1'b1 : 1'b0);

assign tmp_mid2_fu_354_p3 = ((ap_reg_pp0_iter2_exitcond_reg_414[0:0] === 1'b1) ? tmp_mid1_reg_495 : ap_reg_pp0_iter2_tmp8_reg_435);

assign tmp_s_fu_295_p2 = ((p_hw_output_x_scan_s_reg_420 == 11'd1917) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp5_reg_505[0] <= 1'b0;
    ap_reg_pp0_iter3_tmp5_reg_505[0] <= 1'b0;
end

endmodule //Loop_1_proc
