-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.2
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Loop_3_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_hw_input_stencil_stream_to_mul_V_value_V_dout : IN STD_LOGIC_VECTOR (287 downto 0);
    p_hw_input_stencil_stream_to_mul_V_value_V_empty_n : IN STD_LOGIC;
    p_hw_input_stencil_stream_to_mul_V_value_V_read : OUT STD_LOGIC;
    p_mul_stencil_stream_V_value_V_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_mul_stencil_stream_V_value_V_full_n : IN STD_LOGIC;
    p_mul_stencil_stream_V_value_V_write : OUT STD_LOGIC );
end;


architecture behav of Loop_3_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv21_0 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000000";
    constant ap_const_lv21_1F8C94 : STD_LOGIC_VECTOR (20 downto 0) := "111111000110010010100";
    constant ap_const_lv21_1 : STD_LOGIC_VECTOR (20 downto 0) := "000000000000000000001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_9D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011101";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_BE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111110";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_FE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111110";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_hw_input_stencil_stream_to_mul_V_value_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_flag00000000 : BOOLEAN;
    signal exitcond_flatten_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mul_stencil_stream_V_value_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_reg_pp0_iter4_exitcond_flatten_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_reg_105 : STD_LOGIC_VECTOR (20 downto 0);
    signal exitcond_flatten_fu_116_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_flag00011001 : BOOLEAN;
    signal ap_reg_pp0_iter1_exitcond_flatten_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter2_exitcond_flatten_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reg_pp0_iter3_exitcond_flatten_reg_287 : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_next_fu_122_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal p_381_fu_128_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_381_reg_296 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_393_reg_301 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_pp0_iter2_p_393_reg_301 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_417_reg_306 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_429_reg_311 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_reg_316 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_8_reg_321 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_reg_pp0_iter2_tmp_8_reg_321 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_9_reg_326 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_s_reg_331 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_3_reg_336 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp1_fu_240_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp1_reg_341 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp4_fu_245_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp4_reg_346 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_pp0_iter3_tmp4_reg_346 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp5_fu_256_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp5_reg_351 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_reg_pp0_iter3_tmp5_reg_351 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_273_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_reg_356 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_433_fu_282_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_433_reg_361 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_flag00011011 : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_flag00001001 : BOOLEAN;
    signal p_390_fu_212_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_414_fu_226_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_408_fu_219_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_426_fu_233_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp6_fu_251_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_402_fu_261_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp2_fu_268_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp3_fu_278_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_continue)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 xor ap_const_logic_1);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_reg_105_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_0 = exitcond_flatten_fu_116_p2))) then 
                indvar_flatten_reg_105 <= indvar_flatten_next_fu_122_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then 
                indvar_flatten_reg_105 <= ap_const_lv21_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then
                ap_reg_pp0_iter1_exitcond_flatten_reg_287 <= exitcond_flatten_reg_287;
                exitcond_flatten_reg_287 <= exitcond_flatten_fu_116_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0)) then
                ap_reg_pp0_iter2_exitcond_flatten_reg_287 <= ap_reg_pp0_iter1_exitcond_flatten_reg_287;
                ap_reg_pp0_iter2_p_393_reg_301 <= p_393_reg_301;
                ap_reg_pp0_iter2_tmp_8_reg_321 <= tmp_8_reg_321;
                ap_reg_pp0_iter3_exitcond_flatten_reg_287 <= ap_reg_pp0_iter2_exitcond_flatten_reg_287;
                    ap_reg_pp0_iter3_tmp4_reg_346(31 downto 1) <= tmp4_reg_346(31 downto 1);
                ap_reg_pp0_iter3_tmp5_reg_351 <= tmp5_reg_351;
                ap_reg_pp0_iter4_exitcond_flatten_reg_287 <= ap_reg_pp0_iter3_exitcond_flatten_reg_287;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_287 = ap_const_lv1_0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then
                p_381_reg_296 <= p_381_fu_128_p1;
                p_393_reg_301 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(95 downto 64);
                p_417_reg_306 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(223 downto 192);
                p_429_reg_311 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(287 downto 256);
                tmp_3_reg_336 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(254 downto 224);
                tmp_7_reg_316 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(62 downto 32);
                tmp_8_reg_321 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(126 downto 96);
                tmp_9_reg_326 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(157 downto 128);
                tmp_s_reg_331 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(190 downto 160);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter3_exitcond_flatten_reg_287))) then
                p_433_reg_361 <= p_433_fu_282_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter1_exitcond_flatten_reg_287))) then
                tmp1_reg_341 <= tmp1_fu_240_p2;
                    tmp4_reg_346(31 downto 1) <= tmp4_fu_245_p2(31 downto 1);
                tmp5_reg_351 <= tmp5_fu_256_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0) and (ap_const_lv1_0 = ap_reg_pp0_iter2_exitcond_flatten_reg_287))) then
                tmp_reg_356 <= tmp_fu_273_p2;
            end if;
        end if;
    end process;
    tmp4_reg_346(0) <= '0';
    ap_reg_pp0_iter3_tmp4_reg_346(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, exitcond_flatten_fu_116_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_flag00011011, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and not(((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0))) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (exitcond_flatten_fu_116_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_block_pp0_stage0_flag00011011 = ap_const_boolean_0) and (exitcond_flatten_fu_116_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(2);
        ap_block_pp0_stage0_flag00000000 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_flag00001001_assign_proc : process(p_hw_input_stencil_stream_to_mul_V_value_V_empty_n, p_mul_stencil_stream_V_value_V_full_n, ap_enable_reg_pp0_iter1, exitcond_flatten_reg_287, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_exitcond_flatten_reg_287)
    begin
                ap_block_pp0_stage0_flag00001001 <= (((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (exitcond_flatten_reg_287 = ap_const_lv1_0) and (ap_const_logic_0 = p_hw_input_stencil_stream_to_mul_V_value_V_empty_n)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and (ap_const_lv1_0 = ap_reg_pp0_iter4_exitcond_flatten_reg_287) and (ap_const_logic_0 = p_mul_stencil_stream_V_value_V_full_n)));
    end process;


    ap_block_pp0_stage0_flag00011001_assign_proc : process(p_hw_input_stencil_stream_to_mul_V_value_V_empty_n, p_mul_stencil_stream_V_value_V_full_n, ap_enable_reg_pp0_iter1, exitcond_flatten_reg_287, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_exitcond_flatten_reg_287)
    begin
                ap_block_pp0_stage0_flag00011001 <= (((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (exitcond_flatten_reg_287 = ap_const_lv1_0) and (ap_const_logic_0 = p_hw_input_stencil_stream_to_mul_V_value_V_empty_n)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and (ap_const_lv1_0 = ap_reg_pp0_iter4_exitcond_flatten_reg_287) and (ap_const_logic_0 = p_mul_stencil_stream_V_value_V_full_n)));
    end process;


    ap_block_pp0_stage0_flag00011011_assign_proc : process(p_hw_input_stencil_stream_to_mul_V_value_V_empty_n, p_mul_stencil_stream_V_value_V_full_n, ap_enable_reg_pp0_iter1, exitcond_flatten_reg_287, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_exitcond_flatten_reg_287)
    begin
                ap_block_pp0_stage0_flag00011011 <= (((ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (exitcond_flatten_reg_287 = ap_const_lv1_0) and (ap_const_logic_0 = p_hw_input_stencil_stream_to_mul_V_value_V_empty_n)) or ((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and (ap_const_lv1_0 = ap_reg_pp0_iter4_exitcond_flatten_reg_287) and (ap_const_logic_0 = p_mul_stencil_stream_V_value_V_full_n)));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = ap_start) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(p_hw_input_stencil_stream_to_mul_V_value_V_empty_n, exitcond_flatten_reg_287)
    begin
                ap_block_state3_pp0_stage0_iter1 <= ((exitcond_flatten_reg_287 = ap_const_lv1_0) and (ap_const_logic_0 = p_hw_input_stencil_stream_to_mul_V_value_V_empty_n));
    end process;

        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state7_pp0_stage0_iter5_assign_proc : process(p_mul_stencil_stream_V_value_V_full_n, ap_reg_pp0_iter4_exitcond_flatten_reg_287)
    begin
                ap_block_state7_pp0_stage0_iter5 <= ((ap_const_lv1_0 = ap_reg_pp0_iter4_exitcond_flatten_reg_287) and (ap_const_logic_0 = p_mul_stencil_stream_V_value_V_full_n));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_flatten_fu_116_p2)
    begin
        if ((exitcond_flatten_fu_116_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond_flatten_fu_116_p2 <= "1" when (indvar_flatten_reg_105 = ap_const_lv21_1F8C94) else "0";
    indvar_flatten_next_fu_122_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_105) + unsigned(ap_const_lv21_1));
    p_381_fu_128_p1 <= p_hw_input_stencil_stream_to_mul_V_value_V_dout(32 - 1 downto 0);
    p_390_fu_212_p3 <= (tmp_7_reg_316 & ap_const_lv1_0);
    p_402_fu_261_p3 <= (ap_reg_pp0_iter2_tmp_8_reg_321 & ap_const_lv1_0);
    p_408_fu_219_p3 <= (tmp_9_reg_326 & ap_const_lv2_0);
    p_414_fu_226_p3 <= (tmp_s_reg_331 & ap_const_lv1_0);
    p_426_fu_233_p3 <= (tmp_3_reg_336 & ap_const_lv1_0);
    p_433_fu_282_p2 <= std_logic_vector(unsigned(tmp_reg_356) + unsigned(tmp3_fu_278_p2));

    p_hw_input_stencil_stream_to_mul_V_value_V_blk_n_assign_proc : process(p_hw_input_stencil_stream_to_mul_V_value_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_flag00000000, exitcond_flatten_reg_287)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0) and (exitcond_flatten_reg_287 = ap_const_lv1_0))) then 
            p_hw_input_stencil_stream_to_mul_V_value_V_blk_n <= p_hw_input_stencil_stream_to_mul_V_value_V_empty_n;
        else 
            p_hw_input_stencil_stream_to_mul_V_value_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_hw_input_stencil_stream_to_mul_V_value_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond_flatten_reg_287, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1) and (exitcond_flatten_reg_287 = ap_const_lv1_0) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            p_hw_input_stencil_stream_to_mul_V_value_V_read <= ap_const_logic_1;
        else 
            p_hw_input_stencil_stream_to_mul_V_value_V_read <= ap_const_logic_0;
        end if; 
    end process;


    p_mul_stencil_stream_V_value_V_blk_n_assign_proc : process(p_mul_stencil_stream_V_value_V_full_n, ap_block_pp0_stage0_flag00000000, ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_exitcond_flatten_reg_287)
    begin
        if (((ap_block_pp0_stage0_flag00000000 = ap_const_boolean_0) and (ap_const_logic_1 = ap_enable_reg_pp0_iter5) and (ap_const_lv1_0 = ap_reg_pp0_iter4_exitcond_flatten_reg_287))) then 
            p_mul_stencil_stream_V_value_V_blk_n <= p_mul_stencil_stream_V_value_V_full_n;
        else 
            p_mul_stencil_stream_V_value_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_mul_stencil_stream_V_value_V_din <= p_433_reg_361;

    p_mul_stencil_stream_V_value_V_write_assign_proc : process(ap_enable_reg_pp0_iter5, ap_reg_pp0_iter4_exitcond_flatten_reg_287, ap_block_pp0_stage0_flag00011001)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter5) and (ap_const_lv1_0 = ap_reg_pp0_iter4_exitcond_flatten_reg_287) and (ap_block_pp0_stage0_flag00011001 = ap_const_boolean_0))) then 
            p_mul_stencil_stream_V_value_V_write <= ap_const_logic_1;
        else 
            p_mul_stencil_stream_V_value_V_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_240_p2 <= std_logic_vector(unsigned(p_381_reg_296) + unsigned(p_390_fu_212_p3));
    tmp2_fu_268_p2 <= std_logic_vector(unsigned(p_402_fu_261_p3) + unsigned(ap_reg_pp0_iter2_p_393_reg_301));
    tmp3_fu_278_p2 <= std_logic_vector(unsigned(ap_reg_pp0_iter3_tmp4_reg_346) + unsigned(ap_reg_pp0_iter3_tmp5_reg_351));
    tmp4_fu_245_p2 <= std_logic_vector(unsigned(p_414_fu_226_p3) + unsigned(p_408_fu_219_p3));
    tmp5_fu_256_p2 <= std_logic_vector(unsigned(p_417_reg_306) + unsigned(tmp6_fu_251_p2));
    tmp6_fu_251_p2 <= std_logic_vector(unsigned(p_429_reg_311) + unsigned(p_426_fu_233_p3));
    tmp_fu_273_p2 <= std_logic_vector(unsigned(tmp1_reg_341) + unsigned(tmp2_fu_268_p2));
end behav;
