// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_3_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_p2_mul1_stencil_stream_V_value_V_dout,
        p_p2_mul1_stencil_stream_V_value_V_empty_n,
        p_p2_mul1_stencil_stream_V_value_V_read,
        hw_output_V_value_V,
        hw_output_V_value_V_ap_vld,
        hw_output_V_value_V_ap_ack,
        hw_output_V_last_V,
        hw_output_V_last_V_ap_vld,
        hw_output_V_last_V_ap_ack
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state6 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] p_p2_mul1_stencil_stream_V_value_V_dout;
input   p_p2_mul1_stencil_stream_V_value_V_empty_n;
output   p_p2_mul1_stencil_stream_V_value_V_read;
output  [7:0] hw_output_V_value_V;
output   hw_output_V_value_V_ap_vld;
input   hw_output_V_value_V_ap_ack;
output  [0:0] hw_output_V_last_V;
output   hw_output_V_last_V_ap_vld;
input   hw_output_V_last_V_ap_ack;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_p2_mul1_stencil_stream_V_value_V_read;
reg hw_output_V_value_V_ap_vld;
reg hw_output_V_last_V_ap_vld;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_p2_mul1_stencil_stream_V_value_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0_flag00000000;
reg   [0:0] exitcond_flatten_reg_201;
reg   [0:0] ap_reg_pp0_iter2_exitcond_flatten_reg_201;
reg    hw_output_V_value_V_blk_n;
reg    hw_output_V_last_V_blk_n;
reg   [20:0] indvar_flatten_reg_80;
reg   [10:0] p_hw_output_y_scan_1_reg_91;
reg   [10:0] p_hw_output_x_scan_2_reg_103;
wire   [0:0] exitcond_flatten_fu_114_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_sig_ioackin_hw_output_V_value_V_ap_ack;
reg    ap_block_state5_io;
reg    ap_block_pp0_stage0_flag00011001;
reg   [0:0] ap_reg_pp0_iter1_exitcond_flatten_reg_201;
wire   [20:0] indvar_flatten_next_fu_120_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] exitcond7_fu_126_p2;
reg   [0:0] exitcond7_reg_210;
reg   [0:0] ap_reg_pp0_iter1_exitcond7_reg_210;
reg   [0:0] ap_reg_pp0_iter2_exitcond7_reg_210;
wire   [10:0] p_hw_output_x_scan_s_fu_132_p3;
reg   [10:0] p_hw_output_x_scan_s_reg_216;
wire   [10:0] p_hw_output_x_scan_1_fu_140_p2;
wire   [10:0] p_hw_output_y_scan_2_fu_146_p2;
reg   [10:0] p_hw_output_y_scan_2_reg_226;
wire   [0:0] tmp_s_fu_152_p2;
reg   [0:0] tmp_s_reg_231;
reg   [0:0] ap_reg_pp0_iter2_tmp_s_reg_231;
wire   [10:0] p_hw_output_y_scan_s_fu_158_p3;
reg   [10:0] p_hw_output_y_scan_s_reg_236;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] tmp_2_fu_165_p2;
reg   [0:0] tmp_2_reg_241;
reg   [0:0] ap_reg_pp0_iter2_tmp_2_reg_241;
wire   [0:0] tmp_7_mid1_fu_170_p2;
reg   [0:0] tmp_7_mid1_reg_246;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_flag00011011;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg   [10:0] p_hw_output_y_scan_1_phi_fu_95_p4;
reg    ap_block_pp0_stage0_flag00001001;
reg    ap_reg_ioackin_hw_output_V_value_V_ap_ack;
reg    ap_reg_ioackin_hw_output_V_last_V_ap_ack;
wire   [4:0] p_s_fu_180_p4;
wire   [0:0] tmp_7_mid2_fu_175_p3;
wire    ap_CS_fsm_state6;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_reg_ioackin_hw_output_V_value_V_ap_ack = 1'b0;
#0 ap_reg_ioackin_hw_output_V_last_V_ap_ack = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_continue)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (ap_condition_pp0_exit_iter0_state2 ^ 1'b1);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((ap_block_pp0_stage0_flag00011011 == 1'b0)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0))) begin
            if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b0;
            end else if (((ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b1 == hw_output_V_last_V_ap_ack))) begin
                ap_reg_ioackin_hw_output_V_last_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b0;
    end else begin
        if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0))) begin
            if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
                ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b0;
            end else if (((ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b1 == hw_output_V_value_V_ap_ack))) begin
                ap_reg_ioackin_hw_output_V_value_V_ap_ack <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_114_p2))) begin
        indvar_flatten_reg_80 <= indvar_flatten_next_fu_120_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        indvar_flatten_reg_80 <= 21'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'b1 == ap_enable_reg_pp0_iter0) & (1'd0 == exitcond_flatten_fu_114_p2))) begin
        p_hw_output_x_scan_2_reg_103 <= p_hw_output_x_scan_1_fu_140_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        p_hw_output_x_scan_2_reg_103 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_201) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        p_hw_output_y_scan_1_reg_91 <= p_hw_output_y_scan_s_reg_236;
    end else if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
        p_hw_output_y_scan_1_reg_91 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        ap_reg_pp0_iter1_exitcond7_reg_210 <= exitcond7_reg_210;
        ap_reg_pp0_iter1_exitcond_flatten_reg_201 <= exitcond_flatten_reg_201;
        exitcond_flatten_reg_201 <= exitcond_flatten_fu_114_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_block_pp0_stage0_flag00011001 == 1'b0)) begin
        ap_reg_pp0_iter2_exitcond7_reg_210 <= ap_reg_pp0_iter1_exitcond7_reg_210;
        ap_reg_pp0_iter2_exitcond_flatten_reg_201 <= ap_reg_pp0_iter1_exitcond_flatten_reg_201;
        ap_reg_pp0_iter2_tmp_2_reg_241 <= tmp_2_reg_241;
        ap_reg_pp0_iter2_tmp_s_reg_231 <= tmp_s_reg_231;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == exitcond_flatten_fu_114_p2))) begin
        exitcond7_reg_210 <= exitcond7_fu_126_p2;
        p_hw_output_x_scan_s_reg_216 <= p_hw_output_x_scan_s_fu_132_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (exitcond_flatten_reg_201 == 1'd0))) begin
        p_hw_output_y_scan_2_reg_226 <= p_hw_output_y_scan_2_fu_146_p2;
        tmp_2_reg_241 <= tmp_2_fu_165_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (exitcond_flatten_reg_201 == 1'd0) & (1'b1 == ap_enable_reg_pp0_iter1))) begin
        p_hw_output_y_scan_s_reg_236 <= p_hw_output_y_scan_s_fu_158_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_block_pp0_stage0_flag00011001 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_201) & (ap_reg_pp0_iter1_exitcond7_reg_210 == 1'd1))) begin
        tmp_7_mid1_reg_246 <= tmp_7_mid1_fu_170_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_block_pp0_stage0_flag00011001 == 1'b0) & (exitcond_flatten_reg_201 == 1'd0) & (1'd0 == exitcond7_reg_210))) begin
        tmp_s_reg_231 <= tmp_s_fu_152_p2;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_114_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_enable_reg_pp0_iter0) & (1'b0 == ap_enable_reg_pp0_iter1) & (1'b0 == ap_enable_reg_pp0_iter2) & (1'b0 == ap_enable_reg_pp0_iter3))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_reg_ioackin_hw_output_V_value_V_ap_ack)) begin
        ap_sig_ioackin_hw_output_V_value_V_ap_ack = hw_output_V_value_V_ap_ack;
    end else begin
        ap_sig_ioackin_hw_output_V_value_V_ap_ack = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_hw_output_V_last_V_ap_ack))) begin
        hw_output_V_last_V_ap_vld = 1'b1;
    end else begin
        hw_output_V_last_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0))) begin
        hw_output_V_last_V_blk_n = hw_output_V_last_V_ap_ack;
    end else begin
        hw_output_V_last_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (ap_block_pp0_stage0_flag00001001 == 1'b0) & (1'b0 == ap_reg_ioackin_hw_output_V_value_V_ap_ack))) begin
        hw_output_V_value_V_ap_vld = 1'b1;
    end else begin
        hw_output_V_value_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0))) begin
        hw_output_V_value_V_blk_n = hw_output_V_value_V_ap_ack;
    end else begin
        hw_output_V_value_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_block_pp0_stage0_flag00000000 == 1'b0) & (1'd0 == ap_reg_pp0_iter1_exitcond_flatten_reg_201) & (1'b1 == ap_enable_reg_pp0_iter2))) begin
        p_hw_output_y_scan_1_phi_fu_95_p4 = p_hw_output_y_scan_s_reg_236;
    end else begin
        p_hw_output_y_scan_1_phi_fu_95_p4 = p_hw_output_y_scan_1_reg_91;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00000000 == 1'b0) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0))) begin
        p_p2_mul1_stencil_stream_V_value_V_blk_n = p_p2_mul1_stencil_stream_V_value_V_empty_n;
    end else begin
        p_p2_mul1_stencil_stream_V_value_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (ap_block_pp0_stage0_flag00011001 == 1'b0))) begin
        p_p2_mul1_stencil_stream_V_value_V_read = 1'b1;
    end else begin
        p_p2_mul1_stencil_stream_V_value_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & ~((1'b0 == ap_start) | (ap_done_reg == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0)) & ~((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_flatten_fu_114_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b1 == ap_enable_reg_pp0_iter3) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0)) | ((1'b1 == ap_enable_reg_pp0_iter0) & (ap_block_pp0_stage0_flag00011011 == 1'b0) & (exitcond_flatten_fu_114_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0_flag00000000 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_flag00001001 = ((1'b1 == ap_enable_reg_pp0_iter3) & (ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (1'b0 == p_p2_mul1_stencil_stream_V_value_V_empty_n));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011001 = ((1'b1 == ap_enable_reg_pp0_iter3) & (((ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (1'b0 == p_p2_mul1_stencil_stream_V_value_V_empty_n)) | (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_flag00011011 = ((1'b1 == ap_enable_reg_pp0_iter3) & (((ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (1'b0 == p_p2_mul1_stencil_stream_V_value_V_empty_n)) | (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_state1 = ((1'b0 == ap_start) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_io = ((ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (1'b0 == ap_sig_ioackin_hw_output_V_value_V_ap_ack));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = ((ap_reg_pp0_iter2_exitcond_flatten_reg_201 == 1'd0) & (1'b0 == p_p2_mul1_stencil_stream_V_value_V_empty_n));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond7_fu_126_p2 = ((p_hw_output_x_scan_2_reg_103 == 11'd1917) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_114_p2 = ((indvar_flatten_reg_80 == 21'd2064609) ? 1'b1 : 1'b0);

assign hw_output_V_last_V = (ap_reg_pp0_iter2_tmp_2_reg_241 & tmp_7_mid2_fu_175_p3);

assign hw_output_V_value_V = p_s_fu_180_p4;

assign indvar_flatten_next_fu_120_p2 = (indvar_flatten_reg_80 + 21'd1);

assign p_hw_output_x_scan_1_fu_140_p2 = (p_hw_output_x_scan_s_fu_132_p3 + 11'd1);

assign p_hw_output_x_scan_s_fu_132_p3 = ((exitcond7_fu_126_p2[0:0] === 1'b1) ? 11'd0 : p_hw_output_x_scan_2_reg_103);

assign p_hw_output_y_scan_2_fu_146_p2 = (p_hw_output_y_scan_1_phi_fu_95_p4 + 11'd1);

assign p_hw_output_y_scan_s_fu_158_p3 = ((exitcond7_reg_210[0:0] === 1'b1) ? p_hw_output_y_scan_2_fu_146_p2 : p_hw_output_y_scan_1_phi_fu_95_p4);

assign p_s_fu_180_p4 = {{p_p2_mul1_stencil_stream_V_value_V_dout[7:3]}};

assign tmp_2_fu_165_p2 = ((p_hw_output_x_scan_s_reg_216 == 11'd1916) ? 1'b1 : 1'b0);

assign tmp_7_mid1_fu_170_p2 = ((p_hw_output_y_scan_2_reg_226 == 11'd1076) ? 1'b1 : 1'b0);

assign tmp_7_mid2_fu_175_p3 = ((ap_reg_pp0_iter2_exitcond7_reg_210[0:0] === 1'b1) ? tmp_7_mid1_reg_246 : ap_reg_pp0_iter2_tmp_s_reg_231);

assign tmp_s_fu_152_p2 = ((p_hw_output_y_scan_1_phi_fu_95_p4 == 11'd1076) ? 1'b1 : 1'b0);

endmodule //Loop_3_proc
